### ISSUE TITLE
Node red crashing after installing node-red-contrib-widgetlords

### ISSUE THREAD

**Issue by domilim** [widgetlords/node-red-contrib-widgetlords#4]
Dear widgetlords,

After installation of node-red-contrib-widgetlords, my node-red terminal shows a repeated fatal error and is not able to start up. I am not sure is its related to the node-red library or the python library here. Sincerely hope you can provide some assistance.

Thanks,
Dominic Lim

**Comment by widgetlords** [comment]
Which version Node-RED, Node.js, and Raspberry Pi OS are you using? Did you install Node-RED from the repos or using the instructions [here](https://nodered.org/docs/getting-started/raspberrypi)?

**Comment by brzuzak** [comment]
Same problem on Node-Red 2.0.6 - crashing after installation.
Starting as a systemd service.
22 Nov 12:29:04 - [info]
Welcome to Node-RED
===================
22 Nov 12:29:04 - [info] Node-RED version: v2.0.6
22 Nov 12:29:04 - [info] Node.js  version: v14.18.1
22 Nov 12:29:04 - [info] Linux 5.10.63-v7l+ arm LE
22 Nov 12:29:05 - [info] Loading palette nodes
Initializing HAP-NodeJS v0.9.6...
#
# Fatal error in , line 0
# Check failed: result.second.
#
#FailureMessage Object: 0xbec65530
nodered.service: Main process exited, code=killed, status=4/ILL
nodered.service: Failed with result 'signal'.

**Comment by widgetlords** [comment]
> Did you install Node-RED from the repos or using the instructions [here](https://nodered.org/docs/getting-started/raspberrypi)?

Which version of Raspberry Pi OS are you using?

@brzuzak can you answer this?

**Comment by brzuzak** [comment]
I was using the instructions
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by widgetlords** [comment]
See the note here: https://widgetlords.com/pages/node-red-and-the-pi-spi-series.
Node.js version 10 is recommended on Buster and version 12 on Bullseye.
You are using version 14 which is incompatible with this library.

**Comment by brzuzak** [comment]
I switch to version 12.19.1 and that went ok.

**Comment by brzuzak** [comment]
node-red-contrib-widgetlords
1.3.0
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:12)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:12)
Error: ENOENT: no such file or directory, open 'libwidgetlords.so' (line:3

**Comment by widgetlords** [comment]
That is a different issue. Looks like you have not installed libwidgetlords as shown in the instructions on the website.

**Comment by brzuzak** [comment]
Sorry for trouble your right. too fast.

**Comment by widgetlords** [comment]
Fixed in #5
